export type Nutrition = {
    calories: string;
    fiber?: string;
    vitaminC?: string;
    [key: string]: string | undefined;
};

export type FoodItem = {
    name: string;
    slug: string;
    category: "fruits" | "nuts" | "vegetables";
    description: string;
    nutrition: Nutrition;
    pros: string[];
    cons: string[];
    image: string;
};

export const categories = [
    { name: "Fruits", slug: "fruits", icon: "🍎", image: "/images/fruits-category.jpg" },
    { name: "Nuts", slug: "nuts", icon: "🥜", image: "/images/nuts-category.jpg" },
    { name: "Vegetables", slug: "vegetables", icon: "🥦", image: "/images/vegetables-category.jpg" },
];

export const foods: FoodItem[] = [
    // â”€â”€ Fruits â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        name: "Blueberries",
        slug: "blueberries",
        category: "fruits",
        description: "Tiny powerhouse berries bursting with antioxidants and vitamins. One of the most nutrient-dense foods on the planet.",
        nutrition: {
            calories: "57 kcal",
            fiber: "2.4 g",
            vitaminK: "19.3 mcg",
            manganese: "0.3 mg",
        },
        pros: ["Extremely high in antioxidants", "Supports brain health and memory", "Anti-inflammatory properties"],
        cons: ["Can stain teeth and hands", "Short shelf life when fresh"],
        image: "/images/fruits/blueberries.jpg",
    },
    {
        name: "Apple",
        slug: "apple",
        category: "fruits",
        description: "A crunchy, sweet fruit packed with fiber and vitamin C. A timeless snack that supports heart health.",
        nutrition: {
            calories: "52 kcal",
            fiber: "2.4 g",
            vitaminC: "4.6 mg",
            potassium: "107 mg",
        },
        pros: ["High in soluble fiber", "Promotes heart health", "Convenient snack"],
        cons: ["May contain pesticide residue if not organic", "Apple seeds contain trace amounts of cyanide"],
        image: "/images/fruits/apple.jpg",
    },
    {
        name: "Banana",
        slug: "banana",
        category: "fruits",
        description: "A soft, sweet fruit rich in potassium and quick energy. Perfect for pre-workout or smoothies.",
        nutrition: {
            calories: "89 kcal",
            fiber: "2.6 g",
            vitaminB6: "0.4 mg",
            potassium: "358 mg",
        },
        pros: ["Excellent source of potassium", "Easy to digest", "Affordable"],
        cons: ["High in sugar compared to other fruits", "Can cause sugar spikes if eaten in large quantities"],
        image: "/images/fruits/banana.jpg",
    },
    {
        name: "Orange",
        slug: "orange",
        category: "fruits",
        description: "A juicy citrus fruit celebrated for its immune-boosting Vitamin C content and refreshing flavour.",
        nutrition: {
            calories: "47 kcal",
            fiber: "2.4 g",
            vitaminC: "53.2 mg",
            folate: "30 mcg",
        },
        pros: ["Very high in Vitamin C", "Supports immune system", "Rich in flavonoids"],
        cons: ["Acidic â€” may worsen acid reflux", "High natural sugar content"],
        image: "/images/fruits/orange.jpg",
    },
    {
        name: "Mango",
        slug: "mango",
        category: "fruits",
        description: "The king of fruits â€” a tropical delight loaded with Vitamin A, C, and fiber.",
        nutrition: {
            calories: "60 kcal",
            fiber: "1.6 g",
            vitaminA: "54 mcg",
            vitaminC: "36.4 mg",
        },
        pros: ["Rich in Vitamins A and C", "Supports eye health", "Excellent digestive enzymes"],
        cons: ["High in natural sugars", "May trigger allergies in sensitive individuals"],
        image: "/images/fruits/mango.jpg",
    },
    {
        name: "Papaya",
        slug: "papaya",
        category: "fruits",
        description: "A tropical fruit rich in the digestive enzyme papain, Vitamin C, and beta-carotene.",
        nutrition: {
            calories: "43 kcal",
            fiber: "1.7 g",
            vitaminC: "60.9 mg",
            folate: "37 mcg",
        },
        pros: ["Contains papain for improved digestion", "Anti-inflammatory properties", "Excellent skin health benefits"],
        cons: ["Overripe papaya can taste fermented", "Not suitable during early pregnancy in excess"],
        image: "/images/fruits/papaya.jpg",
    },
    {
        name: "Pomegranate",
        slug: "pomegranate",
        category: "fruits",
        description: "An ancient superfruit packed with polyphenols, antioxidants, and heart-protective compounds.",
        nutrition: {
            calories: "83 kcal",
            fiber: "4 g",
            vitaminC: "10.2 mg",
            potassium: "236 mg",
        },
        pros: ["Extremely high in antioxidant polyphenols", "Supports heart health", "Anti-cancer properties"],
        cons: ["Seeds can be difficult to eat", "Juice is high in natural sugar"],
        image: "/images/fruits/pomegranate.jpg",
    },
    {
        name: "Grapes",
        slug: "grapes",
        category: "fruits",
        description: "Sweet, juicy berries that come packed with antioxidants like resveratrol, supporting heart health.",
        nutrition: {
            calories: "69 kcal",
            fiber: "0.9 g",
            vitaminK: "14.6 mcg",
            potassium: "191 mg",
        },
        pros: ["Rich in resveratrol antioxidants", "Supports heart health", "Hydrating and refreshing"],
        cons: ["High glycaemic index for some varieties", "Seedless grapes may be lower in antioxidants"],
        image: "/images/fruits/grapes.jpg",
    },
    {
        name: "Kiwi",
        slug: "kiwi",
        category: "fruits",
        description: "A vibrant green fruit extraordinarily high in Vitamin C and K, with a tangy-sweet flavour.",
        nutrition: {
            calories: "61 kcal",
            fiber: "3 g",
            vitaminC: "92.7 mg",
            vitaminK: "40.3 mcg",
        },
        pros: ["Higher Vitamin C than oranges", "Supports sleep quality", "Good for digestive health"],
        cons: ["May cause oral allergy syndrome", "Skin can irritate sensitive mouths"],
        image: "/images/fruits/kiwi.jpg",
    },
    {
        name: "Strawberries",
        slug: "strawberries",
        category: "fruits",
        description: "Bright red berries that are surprisingly low in calories but very high in Vitamin C and antioxidants.",
        nutrition: {
            calories: "32 kcal",
            fiber: "2 g",
            vitaminC: "58.8 mg",
            manganese: "0.4 mg",
        },
        pros: ["Very low in calories", "High in antioxidants", "Great for skin health"],
        cons: ["Highly perishable", "Pesticide-heavy if not organic"],
        image: "/images/fruits/strawberries.jpg",
    },
    {
        name: "Guava",
        slug: "guava",
        category: "fruits",
        description: "A tropical fruit with an extraordinary Vitamin C content â€” far more than an orange per serving.",
        nutrition: {
            calories: "68 kcal",
            fiber: "5.4 g",
            vitaminC: "228.3 mg",
            potassium: "417 mg",
        },
        pros: ["One of the richest sources of Vitamin C", "Excellent fiber content", "Supports immunity"],
        cons: ["Seeds can be hard on digestion", "Strong smell may be off-putting"],
        image: "/images/fruits/guava.jpg",
    },
    {
        name: "Pineapple",
        slug: "pineapple",
        category: "fruits",
        description: "A tropical fruit containing bromelain, a powerful enzyme with anti-inflammatory and digestive benefits.",
        nutrition: {
            calories: "50 kcal",
            fiber: "1.4 g",
            vitaminC: "47.8 mg",
            manganese: "0.9 mg",
        },
        pros: ["Unique bromelain enzyme aids digestion", "Anti-inflammatory", "Rich in Vitamin C"],
        cons: ["High in sugar", "Acidic â€” can irritate mouth in large quantities"],
        image: "/images/fruits/pineapple.png",
    },
    {
        name: "Watermelon",
        slug: "watermelon",
        category: "fruits",
        description: "A refreshing summer fruit with 92% water content and lycopene, a powerful antioxidant.",
        nutrition: {
            calories: "30 kcal",
            fiber: "0.4 g",
            vitaminC: "8.1 mg",
            lycopene: "4532 mcg",
        },
        pros: ["Extremely hydrating", "Rich in lycopene for heart health", "Very low calorie"],
        cons: ["High glycaemic index can spike blood sugar", "Low in fiber"],
        image: "/images/fruits/watermelon.png",
    },
    {
        name: "Pear",
        slug: "pear",
        category: "fruits",
        description: "A gentle, sweet fruit loaded with fiber and copper that supports gut health and immune function.",
        nutrition: {
            calories: "57 kcal",
            fiber: "3.1 g",
            vitaminC: "4.3 mg",
            copper: "0.1 mg",
        },
        pros: ["High in gut-friendly fiber", "Gentle on the stomach", "Good source of copper"],
        cons: ["High in sorbitol which can cause bloating", "Bruises easily"],
        image: "/images/fruits/pear.jpg",
    },
    {
        name: "Plum",
        slug: "plum",
        category: "fruits",
        description: "A dark-skinned stone fruit rich in Vitamin C, K, and antioxidants that support heart and bone health.",
        nutrition: {
            calories: "46 kcal",
            fiber: "1.4 g",
            vitaminC: "9.5 mg",
            vitaminK: "6.4 mcg",
        },
        pros: ["Rich in antioxidants", "Supports bone health", "Helps regulate blood sugar"],
        cons: ["Dried form (prunes) are very high in sugar", "May have laxative effect in large quantities"],
        image: "/images/fruits/plum.jpg",
    },
    {
        name: "Cherries",
        slug: "cherries",
        category: "fruits",
        description: "Sweet or tart stone fruits rich in antioxidants and melatonin that can improve sleep quality.",
        nutrition: {
            calories: "50 kcal",
            fiber: "1.6 g",
            vitaminC: "7 mg",
            potassium: "222 mg",
        },
        pros: ["Natural source of melatonin for better sleep", "Anti-inflammatory", "Heart-healthy antioxidants"],
        cons: ["Pits can be a choking hazard", "Short seasonal availability"],
        image: "/images/fruits/cherries.jpg",
    },
    {
        name: "Apricot",
        slug: "apricot",
        category: "fruits",
        description: "A golden stone fruit rich in beta-carotene (Vitamin A), supporting vision and immune health.",
        nutrition: {
            calories: "48 kcal",
            fiber: "2 g",
            vitaminA: "96 mcg",
            vitaminC: "10 mg",
        },
        pros: ["High in Vitamin A for eye health", "Low in calories", "Good source of antioxidants"],
        cons: ["Dried apricots are high in sugar", "Short fresh season"],
        image: "/images/fruits/apricot.jpg",
    },
    {
        name: "Dragon Fruit",
        slug: "dragon-fruit",
        category: "fruits",
        description: "A visually stunning tropical fruit with a mild flavour, rich in iron, fiber, and Vitamin C.",
        nutrition: {
            calories: "60 kcal",
            fiber: "3 g",
            vitaminC: "20.5 mg",
            iron: "0.7 mg",
        },
        pros: ["Rich in iron for energy", "Prebiotic fiber feeds gut bacteria", "Exotic and appealing"],
        cons: ["Mild flavour may disappoint", "Can be expensive"],
        image: "/images/fruits/dragon-fruit.jpg",
    },
    {
        name: "Lychee",
        slug: "lychee",
        category: "fruits",
        description: "A fragrant tropical fruit high in Vitamin C and copper with a distinctive floral sweetness.",
        nutrition: {
            calories: "66 kcal",
            fiber: "1.3 g",
            vitaminC: "71.5 mg",
            copper: "0.1 mg",
        },
        pros: ["Very high in Vitamin C", "Rich in antioxidants", "Supports skin health"],
        cons: ["Very high in natural sugar", "Unripe lychee can cause hypoglycaemia"],
        image: "/images/fruits/lychee.jpg",
    },
    {
        name: "Cantaloupe",
        slug: "cantaloupe",
        category: "fruits",
        description: "An orange-fleshed melon bursting with Vitamin A and C that supports eye and immune health.",
        nutrition: {
            calories: "34 kcal",
            fiber: "0.9 g",
            vitaminA: "169 mcg",
            vitaminC: "36.7 mg",
        },
        pros: ["Excellent source of Vitamin A", "Very low in calories", "Hydrating"],
        cons: ["Low in fiber", "High glycaemic index"],
        image: "/images/fruits/cantaloupe.png",
    },
    {
        name: "Blackberries",
        slug: "blackberries",
        category: "fruits",
        description: "Deep purple berries packed with Vitamin C, K, and a rich array of antioxidants.",
        nutrition: {
            calories: "43 kcal",
            fiber: "5.3 g",
            vitaminC: "21 mg",
            vitaminK: "19.8 mcg",
        },
        pros: ["Very high in fiber", "Rich in antioxidants", "Low glycaemic index"],
        cons: ["Seeds can get stuck in teeth", "Stains easily"],
        image: "/images/fruits/blackberries.jpg",
    },
    {
        name: "Raspberries",
        slug: "raspberries",
        category: "fruits",
        description: "Fragrant red berries that are among the highest-fiber fruits available per serving.",
        nutrition: {
            calories: "52 kcal",
            fiber: "6.5 g",
            vitaminC: "26.2 mg",
            manganese: "0.8 mg",
        },
        pros: ["Exceptionally high in fiber", "Rich in antioxidants", "Low in sugar"],
        cons: ["Very perishable", "Delicate and easily crushed"],
        image: "/images/fruits/raspberries.png",
    },
    {
        name: "Cranberries",
        slug: "cranberries",
        category: "fruits",
        description: "Tart red berries renowned for preventing urinary tract infections and supporting gut health.",
        nutrition: {
            calories: "46 kcal",
            fiber: "4.6 g",
            vitaminC: "13.3 mg",
            manganese: "0.4 mg",
        },
        pros: ["Prevents UTIs", "Rich in proanthocyanidins", "Supports gut health"],
        cons: ["Very tart â€” often sweetened commercially", "Cranberry juice products are high in sugar"],
        image: "/images/fruits/cranberries.png",
    },
    {
        name: "Mulberries",
        slug: "mulberries",
        category: "fruits",
        description: "Dark, juicy berries rich in iron, Vitamin C, and resveratrol â€” great for heart and blood health.",
        nutrition: {
            calories: "43 kcal",
            fiber: "1.7 g",
            vitaminC: "36.4 mg",
            iron: "1.85 mg",
        },
        pros: ["Good source of iron", "Rich in resveratrol", "Supports cholesterol levels"],
        cons: ["Stains intensely", "Short and delicate shelf life"],
        image: "/images/fruits/mulberries.jpg",
    },
    {
        name: "Gooseberries",
        slug: "gooseberries",
        category: "fruits",
        description: "Small, tart berries loaded with Vitamin C and fiber that support immunity and digestion.",
        nutrition: {
            calories: "44 kcal",
            fiber: "4.3 g",
            vitaminC: "27.7 mg",
            potassium: "198 mg",
        },
        pros: ["High in fiber", "Rich in Vitamin C", "Supports gut health"],
        cons: ["Very tart â€” may need sweetening", "Not widely available fresh"],
        image: "/images/fruits/gooseberries.jpg",
    },
    {
        name: "Jackfruit",
        slug: "jackfruit",
        category: "fruits",
        description: "The world's largest tree fruit, rich in fiber and potassium. Unripe jackfruit is a popular meat substitute.",
        nutrition: {
            calories: "95 kcal",
            fiber: "1.5 g",
            vitaminC: "13.7 mg",
            potassium: "448 mg",
        },
        pros: ["Excellent meat alternative when unripe", "Good source of potassium", "Unique tropical flavour"],
        cons: ["High in calories", "Sticky latex can cause allergic reactions"],
        image: "/images/fruits/jackfruit.jpg",
    },
    {
        name: "Custard Apple",
        slug: "custard-apple",
        category: "fruits",
        description: "A creamy, sweet tropical fruit rich in Vitamin C and potassium with a custard-like texture.",
        nutrition: {
            calories: "75 kcal",
            fiber: "4.4 g",
            vitaminC: "19.2 mg",
            potassium: "382 mg",
        },
        pros: ["Good source of potassium", "Rich in antioxidants", "Supports energy levels"],
        cons: ["Seeds are toxic if crushed", "High in natural sugar"],
        image: "/images/fruits/custard-apple.jpg",
    },
    {
        name: "Sapodilla",
        slug: "sapodilla",
        category: "fruits",
        description: "A brown, sweet tropical fruit with the taste of caramel, rich in iron and dietary fiber.",
        nutrition: {
            calories: "83 kcal",
            fiber: "5.3 g",
            vitaminC: "14.7 mg",
            iron: "0.8 mg",
        },
        pros: ["Very high in fiber", "Good natural energy source", "Rich in iron"],
        cons: ["Very high in natural sugar", "Can be gritty if not fully ripe"],
        image: "/images/fruits/sapodilla.png",
    },
    {
        name: "Persimmon",
        slug: "persimmon",
        category: "fruits",
        description: "An autumn fruit with a honey-like sweetness and high Vitamin A content for vision and immunity.",
        nutrition: {
            calories: "70 kcal",
            fiber: "3.6 g",
            vitaminA: "81 mcg",
            vitaminC: "7.5 mg",
        },
        pros: ["Rich in Vitamin A", "High in tannins with antimicrobial properties", "Good source of fiber"],
        cons: ["Astringent when unripe", "High in natural sugar"],
        image: "/images/fruits/persimmon.svg",
    },
    {
        name: "Fig",
        slug: "fig",
        category: "fruits",
        description: "An ancient fruit packed with calcium, potassium, and fiber â€” great for bone and digestive health.",
        nutrition: {
            calories: "74 kcal",
            fiber: "2.9 g",
            calcium: "35 mg",
            potassium: "232 mg",
        },
        pros: ["High in calcium for bone health", "Rich in fiber", "Natural sweetness"],
        cons: ["Dried figs are very high in sugar", "Highly perishable when fresh"],
        image: "/images/fruits/fig.jpg",
    },
    {
        name: "Dates",
        slug: "dates",
        category: "fruits",
        description: "Energy-dense dried fruits loaded with iron, potassium, and fiber â€” a natural sweetener substitute.",
        nutrition: {
            calories: "282 kcal",
            fiber: "8 g",
            iron: "1.02 mg",
            potassium: "696 mg",
        },
        pros: ["Excellent natural energy source", "Rich in iron and potassium", "Great sugar substitute"],
        cons: ["Extremely high in calories and sugar", "Can cause tooth decay"],
        image: "/images/fruits/dates.jpg",
    },
    {
        name: "Olives",
        slug: "olives",
        category: "fruits",
        description: "Rich in heart-healthy oleic acid and Vitamin E, olives are a cornerstone of the Mediterranean diet.",
        nutrition: {
            calories: "115 kcal",
            fiber: "3.2 g",
            vitaminE: "3.8 mg",
            iron: "3.3 mg",
        },
        pros: ["Excellent source of heart-healthy monounsaturated fats", "Anti-inflammatory", "High in Vitamin E"],
        cons: ["Very high in sodium when pickled", "High in calories"],
        image: "/images/fruits/olives.jpg",
    },
    {
        name: "Starfruit",
        slug: "starfruit",
        category: "fruits",
        description: "A star-shaped tropical fruit very low in calories and rich in Vitamin C and fiber.",
        nutrition: {
            calories: "31 kcal",
            fiber: "2.8 g",
            vitaminC: "34.4 mg",
            potassium: "133 mg",
        },
        pros: ["Very low in calories", "Rich in antioxidants", "Unique visual appeal"],
        cons: ["Toxic for people with kidney disease", "Sour flavour can be intense"],
        image: "/images/fruits/starfruit.svg",
    },
    {
        name: "Tangerine",
        slug: "tangerine",
        category: "fruits",
        description: "A small, easy-to-peel citrus fruit rich in Vitamin C, folate, and antioxidant flavonoids.",
        nutrition: {
            calories: "53 kcal",
            fiber: "1.8 g",
            vitaminC: "26.7 mg",
            folate: "16 mcg",
        },
        pros: ["Easy to peel and snack on", "Good source of Vitamin C", "Boosts immunity"],
        cons: ["Lower Vitamin C than oranges", "Can be high in sugar"],
        image: "/images/fruits/tangerine.jpg",
    },
    {
        name: "Coconut",
        slug: "coconut",
        category: "fruits",
        description: "A tropical drupe rich in medium-chain triglycerides (MCTs), manganese, and dietary fiber.",
        nutrition: {
            calories: "354 kcal",
            fiber: "9 g",
            manganese: "1.5 mg",
            copper: "0.4 mg",
        },
        pros: ["Rich in MCTs for quick energy", "Supports thyroid function", "Excellent source of manganese"],
        cons: ["Very high in saturated fats", "Very high in calories"],
        image: "/images/fruits/coconut.svg",
    },
    {
        name: "Avocado",
        slug: "avocado",
        category: "fruits",
        description: "A creamy, Vitamin K and folate-rich fruit loaded with heart-healthy monounsaturated fats.",
        nutrition: {
            calories: "160 kcal",
            fiber: "6.7 g",
            vitaminK: "21 mcg",
            folate: "81 mcg",
        },
        pros: ["Rich in healthy monounsaturated fats", "High in folate", "Supports heart health"],
        cons: ["High in calories", "Ripens quickly and browns fast"],
        image: "/images/fruits/avocado.jpg",
    },
    {
        name: "Durian",
        slug: "durian",
        category: "fruits",
        description: "The king of tropical fruits â€” intensely nutritious with Vitamin C, potassium, and fiber, but infamous for its odour.",
        nutrition: {
            calories: "147 kcal",
            fiber: "3.8 g",
            vitaminC: "19.7 mg",
            potassium: "436 mg",
        },
        pros: ["Highly nutritious and energy-dense", "Rich in potassium", "Good source of fiber"],
        cons: ["Extremely pungent smell", "High in calories and sugar"],
        image: "/images/fruits/durian.jpg",
    },
    {
        name: "Passion Fruit",
        slug: "passion-fruit",
        category: "fruits",
        description: "A small, tropical fruit packed with iron, Vitamin C, and fiber in every seedy spoonful.",
        nutrition: {
            calories: "97 kcal",
            fiber: "10.4 g",
            vitaminC: "30 mg",
            iron: "1.6 mg",
        },
        pros: ["Exceptional fiber content", "Good source of iron", "Rich in antioxidants"],
        cons: ["Very tart and seedy", "High in natural sugar"],
        image: "/images/fruits/passion-fruit.jpg",
    },
    {
        name: "Loquat",
        slug: "loquat",
        category: "fruits",
        description: "A small orange fruit rich in Vitamin A, potassium, and fiber with antioxidant beta-carotene.",
        nutrition: {
            calories: "47 kcal",
            fiber: "1.7 g",
            vitaminA: "76 mcg",
            potassium: "266 mg",
        },
        pros: ["Good source of Vitamin A", "Supports respiratory health", "Low in calories"],
        cons: ["Seeds are toxic if ingested", "Short seasonal availability"],
        image: "/images/fruits/loquat.jpg",
    },
    {
        name: "Quince",
        slug: "quince",
        category: "fruits",
        description: "An ancient golden fruit rich in Vitamin C, copper, and fiber â€” usually cooked before eating.",
        nutrition: {
            calories: "57 kcal",
            fiber: "1.9 g",
            vitaminC: "15 mg",
            copper: "0.1 mg",
        },
        pros: ["High in antioxidants", "Good for digestive health", "Rich in Vitamin C"],
        cons: ["Too hard and astringent to eat raw", "Rarely found in supermarkets"],
        image: "/images/fruits/quince.svg",
    },
    {
        name: "Mandarin",
        slug: "mandarin",
        category: "fruits",
        description: "A sweet, easy-to-peel citrus fruit full of Vitamin C, folate, and immune-boosting flavonoids.",
        nutrition: {
            calories: "53 kcal",
            fiber: "1.8 g",
            vitaminC: "26.7 mg",
            folate: "16 mcg",
        },
        pros: ["Easy to eat on the go", "Good immunity boost", "Kid-friendly fruit"],
        cons: ["Can be high in sugar", "Less fiber compared to other fruits"],
        image: "/images/fruits/mandarin.svg",
    },
    {
        name: "Nectarine",
        slug: "nectarine",
        category: "fruits",
        description: "A smooth-skinned stone fruit similar to a peach, rich in Vitamin C, potassium, and fiber.",
        nutrition: {
            calories: "44 kcal",
            fiber: "1.7 g",
            vitaminC: "5.4 mg",
            potassium: "201 mg",
        },
        pros: ["No fuzzy skin â€” easy to eat", "Low in calories", "Good source of antioxidants"],
        cons: ["Bruises easily", "Short shelf life once ripe"],
        image: "/images/fruits/nectarine.svg",
    },
    {
        name: "Peach",
        slug: "peach",
        category: "fruits",
        description: "A velvety summer stone fruit with gentle sweetness, rich in Vitamin C, A, and fiber.",
        nutrition: {
            calories: "39 kcal",
            fiber: "1.5 g",
            vitaminC: "6.6 mg",
            vitaminA: "16 mcg",
        },
        pros: ["Low in calories", "Good source of Vitamins A and C", "Naturally hydrating"],
        cons: ["Can trigger peach allergy (oral allergy syndrome)", "Short shelf life"],
        image: "/images/fruits/peach.jpg",
    },
    // ── Nuts ─────────────────────────────────────────────────────────────────────
    {
        name: "Almonds",
        slug: "almonds",
        category: "nuts",
        description: "A popular, nutrient-dense tree nut known for its satisfying crunch and high vitamin E content.",
        nutrition: { calories: "579 kcal", vitaminE: "25.6 mg", magnesium: "268 mg", protein: "21.1 g" },
        pros: ["Excellent source of Vitamin E", "Rich in healthy monounsaturated fats", "Good plant-based protein"],
        cons: ["High in calories (easy to overeat)", "Contains phytic acid which limits mineral absorption"],
        image: "/images/nuts/almonds.jpg",
    },
    {
        name: "Walnuts",
        slug: "walnuts",
        category: "nuts",
        description: "Brain-shaped nuts distinguished by their exceptionally high concentration of anti-inflammatory Omega-3 fatty acids.",
        nutrition: { calories: "654 kcal", omega3: "9000 mg", antioxidants: "High", protein: "15.2 g" },
        pros: ["Phenomenal source of Omega-3s (ALA)", "Promotes brain health", "Reduces inflammation"],
        cons: ["Very high stringency/bitterness in the skin", "Go rancid quickly if not stored cold"],
        image: "/images/nuts/walnuts.jpg",
    },
    {
        name: "Pistachios",
        slug: "pistachios",
        category: "nuts",
        description: "Vibrant green nuts encased in a hard shell, offering lower calories than most nuts and excellent potassium.",
        nutrition: { calories: "562 kcal", vitaminB6: "1.7 mg", potassium: "1025 mg", fiber: "10 g" },
        pros: ["Lower in calories than most nuts", "High in potassium", "Shelling them slows down consumption"],
        cons: ["Often heavily salted", "Expensive compared to other nuts"],
        image: "/images/nuts/pistachios.jpg",
    },
    {
        name: "Cashews",
        slug: "cashews",
        category: "nuts",
        description: "A kidney-shaped nut known for its buttery texture, mild sweetness, and rich mineral profile including copper and magnesium.",
        nutrition: { calories: "553 kcal", copper: "2.2 mg", magnesium: "292 mg", protein: "18.2 g" },
        pros: ["Creamy texture ideal for vegan dairy substitutes", "Rich in copper for bone health", "High in magnesium"],
        cons: ["Slightly higher carbohydrate content than other nuts", "Often sold roasted in unhealthy oils"],
        image: "/images/nuts/cashews.jpg",
    },
    {
        name: "Hazelnuts",
        slug: "hazelnuts",
        category: "nuts",
        description: "Sweet, earthy nuts favored in desserts but powerfully nutritious on their own, boasting significant vitamin E and fiber.",
        nutrition: { calories: "628 kcal", vitaminE: "15 mg", magnesium: "163 mg", fiber: "9.7 g" },
        pros: ["Very high in proanthocyanidin antioxidants", "Supports heart health", "High in vitamin E"],
        cons: ["Can cause allergic reactions (tree nut allergy)", "Commonly consumed with excess sugar (Nutella)"],
        image: "/images/nuts/hazelnuts.jpg",
    },
    {
        name: "Brazil Nuts",
        slug: "brazil-nuts",
        category: "nuts",
        description: "Massive Amazonian seeds famous for being the most concentrated natural dietary source of selenium on the planet.",
        nutrition: { calories: "659 kcal", selenium: "1917 mcg", magnesium: "376 mg", protein: "14.3 g" },
        pros: ["Eating just one provides daily selenium needs", "Supports thyroid function", "High in magnesium"],
        cons: ["Eating too many causes selenium toxicity", "Very high in calories"],
        image: "/images/nuts/brazil-nuts.jpg",
    },
    {
        name: "Macadamia Nuts",
        slug: "macadamia-nuts",
        category: "nuts",
        description: "Rich, buttery, and incredibly luxurious, these nuts boast the highest monounsaturated fat content of any seed or nut.",
        nutrition: { calories: "718 kcal", monounsaturatedFats: "58.9 g", thiamine: "1.2 mg", fiber: "8.6 g" },
        pros: ["Exceptional healthy fat profile", "Very low in carbohydrates", "Rich in thiamine (Vitamin B1)"],
        cons: ["Extremely calorie dense", "Highly toxic to dogs"],
        image: "/images/nuts/macadamia-nuts.jpg",
    },
    {
        name: "Pine Nuts",
        slug: "pine-nuts",
        category: "nuts",
        description: "Small, tear-shaped seeds harvested from pine cones that add a delicate, buttery crunch to pesto and salads.",
        nutrition: { calories: "673 kcal", vitaminE: "9.3 mg", magnesium: "251 mg", protein: "13.7 g" },
        pros: ["Contains pinolenic acid which suppresses appetite", "Essential for authentic pesto", "High in magnesium"],
        cons: ["Can cause 'pine nut syndrome' (temporary bitter metallic taste)", "Very expensive"],
        image: "/images/nuts/pine-nuts.jpg",
    },
    {
        name: "Chestnuts",
        slug: "chestnuts",
        category: "nuts",
        description: "Unlike other nuts, chestnuts have a crumbly, starchy texture, are low in fat, and provide significant vitamin C.",
        nutrition: { calories: "213 kcal", vitaminC: "43 mg", potassium: "518 mg", fiber: "8.1 g" },
        pros: ["Much lower in calories/fat than other nuts", "Only nut that contains vitamin C", "Rich, comforting flavor when roasted"],
        cons: ["Must be cooked before eating", "High in carbohydrates compared to other nuts"],
        image: "/images/nuts/chestnuts.jpg",
    },
    {
        name: "Pecans",
        slug: "pecans",
        category: "nuts",
        description: "A sweet, rich nut native to North America with an incredibly high antioxidant score and plenty of fiber.",
        nutrition: { calories: "691 kcal", vitaminE: "1.4 mg", antioxidants: "High", fiber: "9.6 g" },
        pros: ["One of the highest antioxidant capacities among nuts", "Lowers LDL cholesterol", "Rich buttery flavor"],
        cons: ["Very high calorie density", "Usually consumed in heavy sugary desserts (pecan pie)"],
        image: "/images/nuts/pecans.jpg",
    },
    {
        name: "Tiger Nuts",
        slug: "tiger-nuts",
        category: "nuts",
        description: "Not actually a nut, but a small root vegetable (tuber) rich in prebiotic fiber that tastes remarkably like coconut and almond.",
        nutrition: { calories: "480 kcal", vitaminC: "14 mg", magnesium: "105 mg", fiber: "33 g" },
        pros: ["Exceptional source of prebiotic resistant starch", "Nut-free (safe for tree-nut allergies)", "Great source of magnesium"],
        cons: ["Texture can be tough and chewy if not soaked", "Relatively high in carbohydrates"],
        image: "/images/nuts/tiger-nuts.jpg",
    },
    {
        name: "Kola Nuts",
        slug: "kola-nuts",
        category: "nuts",
        description: "The caffeine-rich nut of the kola tree, historically chewed in West Africa for energy and the original flavor of colas.",
        nutrition: { calories: "150 kcal", caffeine: "High", theobromine: "Present", antioxidants: "Medium" },
        pros: ["Natural stimulant and energy booster", "Aids digestion", "Cultural significance"],
        cons: ["High caffeine can cause jitters or insomnia", "Extremely bitter taste"],
        image: "/images/nuts/kola-nuts.jpg",
    },
    {
        name: "Ginkgo Nuts",
        slug: "ginkgo-nuts",
        category: "nuts",
        description: "The seeds of the ancient ginkgo tree, prized in Asian cooking for their chewy texture and mild flavor.",
        nutrition: { calories: "182 kcal", vitaminC: "15 mg", antioxidants: "High", fiber: "1 g" },
        pros: ["Low in fat", "Traditional medicinal uses", "Contains powerful antioxidants"],
        cons: ["Toxic if eaten raw or in large quantities (ginkgotoxin)", "Flesh surrounding seed smells terribly like vomit"],
        image: "/images/nuts/ginkgo-nuts.jpg",
    },
    {
        name: "Acorns",
        slug: "acorns",
        category: "nuts",
        description: "The abundant nut of the oak tree. Often ignored today, but a historical indigenous staple rich in complex carbs.",
        nutrition: { calories: "387 kcal", carbohydrates: "41 g", potassium: "539 mg", fiber: "0 g" },
        pros: ["Sustainable, abundant food source", "Rich in complex carbohydrates", "Gluten-free flour alternative"],
        cons: ["Must be extensively leached of toxic, bitter tannins before consumption", "Extremely labor-intensive to prepare"],
        image: "/images/nuts/acorns.jpg",
    },
    {
        name: "Candle Nuts",
        slug: "candle-nuts",
        category: "nuts",
        description: "A highly oily nut used extensively in Southeast Asian curries to thicken sauces and add a rich, macadamia-like flavor.",
        nutrition: { calories: "719 kcal", healthyFats: "High", protein: "19 g", magnesium: "High" },
        pros: ["Excellent curry thickener", "High in magnesium", "Rich in healthy oils"],
        cons: ["Mildly toxic and causes severe cramps if eaten raw", "Must be cooked thoroughly"],
        image: "/images/nuts/candle-nuts.jpg",
    },
    {
        name: "Baru Nuts",
        slug: "baru-nuts",
        category: "nuts",
        description: "A super-nut from the Brazilian savanna boasting more protein and fiber than almonds, with a peanut-cocoa flavor.",
        nutrition: { calories: "570 kcal", protein: "24 g", fiber: "14 g", magnesium: "High" },
        pros: ["Higher protein and fiber than almonds", "Lower in calories than most nuts", "Delicious peanut-cocoa taste"],
        cons: ["Must be roasted to neutralize anti-nutrients", "Can be difficult to source and expensive"],
        image: "/images/nuts/baru-nuts.jpg",
    },
    {
        name: "Hickory Nuts",
        slug: "hickory-nuts",
        category: "nuts",
        description: "Wild nuts native to North America that share a lineage with pecans, offering an intense, buttery, maple-like flavor.",
        nutrition: { calories: "657 kcal", protein: "12.7 g", healthyFats: "64 g", fiber: "6.4 g" },
        pros: ["Incredible rich, buttery flavor", "High in healthy fats", "Great source of plant protein"],
        cons: ["Notoriously difficult shells to crack", "Rarely sold commercially (usually foraged)"],
        image: "/images/nuts/hickory-nuts.jpg",
    },
    {
        name: "Ogbono Seeds (African Bush Mango)",
        slug: "african-bush-mango",
        category: "nuts",
        description: "Seeds ground into powder and used to make thick, mucilaginous soups in West African cuisine.",
        nutrition: { calories: "600 kcal", healthyFats: "High", protein: "8.5 g", fiber: "High" },
        pros: ["Excellent thickening agent", "High in healthy fats", "May aid in weight management"],
        cons: ["Slimy texture in soups isn't for everyone", "High in calories"],
        image: "/images/nuts/african-bush-mango.jpg",
    },
    {
        name: "Malabar Chestnuts",
        slug: "malabar-chestnuts",
        category: "nuts",
        description: "Also known as the 'Money Tree' nut, offering a peanut-like flavor when raw and a chestnut texture when roasted.",
        nutrition: { calories: "350 kcal", protein: "16 g", potassium: "High", fiber: "High" },
        pros: ["Good source of protein", "Lower fat than standard nuts", "Easy to roast and eat"],
        cons: ["Contains cyclopropenoid fatty acids (can cause issues if eaten raw in bulk)", "Mostly grown as an ornamental plant"],
        image: "/images/nuts/malabar-chestnuts.jpg",
    },
    {
        name: "Sacha Inchi",
        slug: "sacha-inchi",
        category: "nuts",
        description: "A star-shaped seed from the Amazon, highly revered as one of the best plant-based sources of Omega-3 fatty acids.",
        nutrition: { calories: "500 kcal", omega3: "High", protein: "27 g", fiber: "8 g" },
        pros: ["Extraordinary Omega-3 content", "Very high in complete protein for a plant", "Easily digestible"],
        cons: ["Must be roasted (raw seeds cause nausea)", "Distinctive earthy, slightly fishy taste"],
        image: "/images/nuts/sacha-inchi.jpg",
    },
    {
        name: "Monkey Puzzle Nuts",
        slug: "monkey-puzzle-nuts",
        category: "nuts",
        description: "Large pine nuts harvested from the ancient Monkey Puzzle tree, with a starchy texture resembling roasted chestnuts.",
        nutrition: { calories: "600 kcal", protein: "15 g", healthyFats: "High", fiber: "High" },
        pros: ["High in complex carbohydrates", "Excellent source of energy", "Culturally significant in Chile"],
        cons: ["Only produced by female trees after 40 years", "Trees are endangered"],
        image: "/images/nuts/monkey-puzzle-nuts.jpg",
    },
    {
        name: "Pili Nuts",
        slug: "pili-nuts",
        category: "nuts",
        description: "An incredibly tender, buttery nut from the Philippines holding the record for the highest fat and lowest carb content.",
        nutrition: { calories: "719 kcal", magnesium: "302 mg", protein: "10.8 g", healthyFats: "79 g" },
        pros: ["Ultimate keto nut (lowest carbs, highest fat)", "Melt-in-your-mouth texture", "Very high in magnesium and Vitamin E"],
        cons: ["Extremely calorie dense", "Very difficult to harvest and thus expensive"],
        image: "/images/nuts/pili-nuts.jpg",
    },
    {
        name: "Chilean Hazelnuts",
        slug: "chilean-hazelnuts",
        category: "nuts",
        description: "Also known as Gevuina, these macadamia relatives produce a dark, highly prized nut resembling a standard hazelnut in taste.",
        nutrition: { calories: "650 kcal", vitaminE: "High", protein: "12 g", fiber: "High" },
        pros: ["Rich in Vitamin E antioxidants", "High in heart-healthy monounsaturated fats", "Great substitute for macadamias"],
        cons: ["Very regional and difficult to find globally", "Hard, thick shells"],
        image: "/images/nuts/chilean-hazelnuts.jpg",
    },
    {
        name: "Japanese Walnuts",
        slug: "japanese-walnuts",
        category: "nuts",
        description: "Smooth-shelled, heart-shaped walnuts (Heartnuts) that taste sweeter and lack the bitter skin of English walnuts.",
        nutrition: { calories: "654 kcal", omega3: "High", protein: "15 g", fiber: "6 g" },
        pros: ["Sweeter and less bitter than common walnuts", "Crack easily and whole", "High in Omega-3"],
        cons: ["Trees require specific climates", "Lower commercial yield"],
        image: "/images/nuts/japanese-walnuts.jpg",
    },
    {
        name: "Butternuts",
        slug: "butternuts",
        category: "nuts",
        description: "Also known as white walnuts, a native North American nut prized for its exceptionally high fat content and sweet flavor.",
        nutrition: { calories: "600 kcal", protein: "24 g", healthyFats: "57 g", fiber: "High" },
        pros: ["Very high protein content for a walnut", "Deliciously rich, oily flavor", "Great for baking"],
        cons: ["Trees are highly susceptible to butternut canker disease", "Messy to harvest as the husks stain hands heavily"],
        image: "/images/nuts/butternuts.jpg",
    },
    {
        name: "Buah Keluak",
        slug: "buah-keluak",
        category: "nuts",
        description: "A large black nut utilized in Peranakan cuisine, known for its dark, earthy, truffle-like flavor after extensive processing.",
        nutrition: { calories: "400 kcal", protein: "High", healthyFats: "High", fiber: "High" },
        pros: ["Incredible, complex umami flavor", "Staple of authentic Ayam Buah Keluak", "Rich in minerals"],
        cons: ["Contains deadly hydrogen cyanide when raw", "Requires days of soaking and boiling to become safe"],
        image: "/images/nuts/buah-keluak.jpg",
    },
    {
        name: "Water Caltrop (Singhara)",
        slug: "water-caltrop",
        category: "nuts",
        description: "A bat-shaped aquatic seed consumed in Asia, very low in calories and fat, but high in satisfying complex carbs.",
        nutrition: { calories: "97 kcal", vitaminC: "Low", iron: "Modest", fiber: "High" },
        pros: ["Extremely low in fat and calories", "Crunchy texture when raw, starchy when boiled", "Gluten-free flour alternative"],
        cons: ["Must be boiled to destroy aquatic parasites", "Sharp horns can cause injury during prep"],
        image: "/images/nuts/water-caltrop.jpg",
    },
    {
        name: "Lotus Seeds",
        slug: "lotus-seeds",
        category: "nuts",
        description: "Edible seeds of the lotus flower used in traditional Chinese medicine and desserts, offering a mild, starchy flavor.",
        nutrition: { calories: "350 kcal", protein: "15 g", magnesium: "56 mg", fiber: "High" },
        pros: ["Low in fat", "High in protein and magnesium", "Great for sweet pastes (mooncake fillings)"],
        cons: ["Bitter green germ inside must be meticulously removed", "Can cause constipation in large amounts"],
        image: "/images/nuts/lotus-seeds.jpg",
    },
    {
        name: "Fox Nuts (Makhana)",
        slug: "makhana",
        category: "nuts",
        description: "Popped lotus seeds forming a light, airy snack wildly popular in India as a healthy alternative to popcorn.",
        nutrition: { calories: "347 kcal", protein: "9.7 g", magnesium: "High", fiber: "14.5 g" },
        pros: ["Very low in cholesterol, fat, and sodium", "Excellent healthy popcorn alternative", "High in magnesium and protein"],
        cons: ["Bland without excessive seasoning", "Can become soggy quickly in humid environments"],
        image: "/images/nuts/makhana.jpg",
    },
    {
        name: "Kukui Nuts",
        slug: "kukui-nuts",
        category: "nuts",
        description: "The official state tree nut of Hawaii, strictly roasted and used as a condiment (inamona) in traditional poke.",
        nutrition: { calories: "719 kcal", healthyFats: "High", protein: "19 g", fiber: "High" },
        pros: ["Essential ingredient for authentic Hawaiian poke", "Rich in healthy oils", "Oils are fantastic for skin (candlenut oil)"],
        cons: ["Highly toxic raw (severe laxative effect)", "Should only be eaten sparingly even when roasted"],
        image: "/images/nuts/kukui-nuts.jpg",
    },
    {
        name: "Peanuts",
        slug: "peanuts",
        category: "nuts",
        description: "Botanically legumes but culinary nuts, peanuts are one of the most affordable and prevalent sources of plant protein globally.",
        nutrition: { calories: "567 kcal", protein: "25.8 g", niacin: "12 mg", magnesium: "168 mg" },
        pros: ["Very high in protein", "Inexpensive and accessible", "Excellent source of Niacin (Vitamin B3)"],
        cons: ["One of the most common and severe food allergens", "Prone to aflatoxin (mold) contamination"],
        image: "/images/nuts/peanuts.jpg",
    },
    {
        name: "Soy Nuts",
        slug: "soy-nuts",
        category: "nuts",
        description: "Roasted mature soybeans providing a massive crunchy punch of complete protein and dietary fiber.",
        nutrition: { calories: "446 kcal", protein: "35.2 g", iron: "3.9 mg", fiber: "17.7 g" },
        pros: ["One of the highest protein contents among 'nuts'", "Contains complete plant-based protein", "Very high in fiber"],
        cons: ["Legume, not a true nut", "Can be difficult to digest for some"],
        image: "/images/nuts/soy-nuts.jpg",
    },
    {
        name: "Cedar Nuts",
        slug: "cedar-nuts",
        category: "nuts",
        description: "Siberian pine nuts containing a higher oil concentration than standard pine nuts, renowned for their medicinal oil.",
        nutrition: { calories: "673 kcal", vitaminE: "9.3 mg", magnesium: "251 mg", protein: "13.7 g" },
        pros: ["Rich in pinolenic acid which supports digestion", "Excellent source of Vitamin E", "Distinctly sweet, rich flavor"],
        cons: ["Expensive to import", "Very high calorie density"],
        image: "/images/nuts/cedar-nuts.jpg",
    },
    {
        name: "Chironji (Charoli)",
        slug: "chironji",
        category: "nuts",
        description: "Small almond-flavored seeds beloved in Indian desserts for their soft texture and unique nutty-pine flavor.",
        nutrition: { calories: "620 kcal", protein: "19 g", iron: "High", fiber: "High" },
        pros: ["Cooling effect on the body in Ayurvedic medicine", "Excellent source of protein and iron", "Great for enriching sweets"],
        cons: ["Difficult to source outside of India", "High fat content means short shelf life"],
        image: "/images/nuts/chironji.jpg",
    },
    {
        name: "Bitter Kola",
        slug: "bitter-kola",
        category: "nuts",
        description: "A seed highly valued in traditional African medicine, chewed for its stimulating effects and reputed healing properties.",
        nutrition: { calories: "150 kcal", caffeine: "High", antioxidants: "High", fiber: "Present" },
        pros: ["Strong natural antibacterial/antiviral properties", "Relieves coughs and throat issues", "Mild stimulant"],
        cons: ["Extremely bitter and astringent taste", "Can interact with certain medications"],
        image: "/images/nuts/bitter-kola.jpg",
    },
    {
        name: "Shea Nuts",
        slug: "shea-nuts",
        category: "nuts",
        description: "The seeds from the African karite tree, primarily crushed to extract shea butter for chocolate and cosmetics.",
        nutrition: { calories: "700 kcal", healthyFats: "Very High", protein: "Moderate", magnesium: "High" },
        pros: ["Shea butter is a fantastic vegan fat alternative in chocolate", "Incredible for skin moisturization", "Rich in vitamins A and E"],
        cons: ["Rarely consumed whole as a nut", "Requires massive processing to become edible butter"],
        image: "/images/nuts/shea-nuts.jpg",
    },
    {
        name: "Marula Nuts",
        slug: "marula-nuts",
        category: "nuts",
        description: "The highly nutritious kernel inside the African Marula fruit, boasting massive protein and antioxidants.",
        nutrition: { calories: "600 kcal", protein: "28 g", healthyFats: "High", fiber: "High" },
        pros: ["Extremely high protein content", "Rich in magnesium, phosphorus and potassium", "Oil is prized for cosmetics"],
        cons: ["Extremely difficult to extract from the hard shell", "Low commercial availability"],
        image: "/images/nuts/marula-nuts.jpg",
    },
    {
        name: "African Walnut",
        slug: "african-walnut",
        category: "nuts",
        description: "A dark, highly nutritious nut distinct from regular walnuts, typically boiled before consumption as a snack.",
        nutrition: { calories: "650 kcal", protein: "24 g", healthyFats: "High", fiber: "High" },
        pros: ["Excellent source of protein", "Improves cardiovascular health", "Rich in antioxidants"],
        cons: ["Bitter aftertaste when drinking water post-consumption", "Must be cooked to be palatable"],
        image: "/images/nuts/african-walnut.jpg",
    },
    {
        name: "Singada Nuts",
        slug: "singada-nuts",
        category: "nuts",
        description: "Another regional name for the Water Caltrop/Chestnut, heavily utilized during fasting periods in India.",
        nutrition: { calories: "97 kcal", vitaminC: "Low", iron: "Moderate", fiber: "High" },
        pros: ["Flour (Singhara atta) is essential for Hindu fasting foods", "Cooling properties", "Low fat"],
        cons: ["Bland taste on its own", "Requires extensive processing for flour"],
        image: "/images/nuts/singada-nuts.jpg",
    },
    {
        name: "Kukui Seeds",
        slug: "kukui-seeds",
        category: "nuts",
        description: "A reiteration of the Kukui Nut specifically highlighting the potent oil content used for lighting in ancient times.",
        nutrition: { calories: "719 kcal", healthyFats: "Very High", protein: "19 g", fiber: "High" },
        pros: ["Oil is a traditional skin protectant against elements", "Burns brightly (Candlenut)", "Culinary staple in poke"],
        cons: ["Toxic raw", "High calorie density"],
        image: "/images/nuts/kukui-seeds.jpg",
    },
    {
        name: "Ogbono Seeds",
        slug: "ogbono-seeds",
        category: "nuts",
        description: "The heart of the African Mango, these seeds form the mucilaginous base of the famous Ogbono soup.",
        nutrition: { calories: "600 kcal", healthyFats: "High", protein: "8.5 g", fiber: "High" },
        pros: ["Incredible soup thickener", "Linked to healthy weight management", "Requires minimal spices due to intrinsic flavor"],
        cons: ["Unique slimy texture can be polarizing", "Can be expensive outside of West Africa"],
        image: "/images/nuts/ogbono-seeds.jpg",
    },
    {
        name: "Siberian Pine Nuts",
        slug: "siberian-pine-nuts",
        category: "nuts",
        description: "A slightly smaller, rounder, and far more oily and tender pine nut harvested from the vast Siberian taiga.",
        nutrition: { calories: "673 kcal", vitaminE: "9.3 mg", magnesium: "251 mg", protein: "13.7 g" },
        pros: ["Higher oil content yields deeply buttery flavor", "Rich in pinolenic acid", "Rarely cause 'pine nut syndrome'"],
        cons: ["Difficult to harvest, increasing cost", "Very dense fat profile"],
        image: "/images/nuts/siberian-pine-nuts.jpg",
    },
    {
        name: "Wild Almonds",
        slug: "wild-almonds",
        category: "nuts",
        description: "The undomesticated ancestor of the modern sweet almond, characterized by extreme bitterness and high toxicity.",
        nutrition: { calories: "579 kcal", vitaminE: "High", magnesium: "High", protein: "High" },
        pros: ["Incredibly hardy and drought resistant (agricultural use)", "Source of bitter almond extract (after toxin removal)"],
        cons: ["Extremely toxic (contains amydalin which turns into cyanide)", "Lethal to humans if consumed raw"],
        image: "/images/nuts/wild-almonds.jpg",
    },
    {
        name: "Wild Walnuts",
        slug: "wild-walnuts",
        category: "nuts",
        description: "Foraged varieties that often possess thicker, harder shells and a more robust, astringent flavor than domesticated counterparts.",
        nutrition: { calories: "654 kcal", omega3: "Very High", protein: "15 g", fiber: "High" },
        pros: ["Incredible concentration of Omega-3s", "Stronger, more complex walnut flavor", "No agricultural chemicals"],
        cons: ["Shells are brutally difficult to crack cleanly", "High levels of bitter tannins"],
        image: "/images/nuts/wild-walnuts.jpg",
    },
    // ── Vegetables ───────────────────────────────────────────────────────────────
    {
        name: "Spinach",
        slug: "spinach",
        category: "vegetables",
        description: "A dark leafy green loaded with iron, vitamin K, and vitamin A. Extremely versatile and nutrient-dense.",
        nutrition: { calories: "23 kcal", iron: "2.7 mg", vitaminK: "483 mcg", vitaminA: "469 mcg" },
        pros: ["Excellent source of iron", "Promotes bone health", "Rich in antioxidants"],
        cons: ["High in oxalates", "Cooking reduces some vitamin C"],
        image: "/images/vegetables/spinach.jpg",
    },
    {
        name: "Broccoli",
        slug: "broccoli",
        category: "vegetables",
        description: "A cruciferous powerhouse packed with vitamin C and K. Known for its cancer-fighting compounds.",
        nutrition: { calories: "34 kcal", vitaminC: "89.2 mg", vitaminK: "101.6 mcg", fiber: "2.6 g" },
        pros: ["High in vitamin C for immunity", "Supports healthy digestion", "Contains sulforaphane"],
        cons: ["Can cause gas or bloating", "May go bad quickly if not stored properly"],
        image: "/images/vegetables/broccoli.jpg",
    },
    {
        name: "Carrot",
        slug: "carrot",
        category: "vegetables",
        description: "Crunchy, sweet root vegetable famous for its high beta-carotene content, which is excellent for vision.",
        nutrition: { calories: "41 kcal", betaCarotene: "8285 mcg", vitaminA: "835 mcg", fiber: "2.8 g" },
        pros: ["Promotes excellent eye health", "High in antioxidant beta-carotene", "Convenient raw snack"],
        cons: ["High natural sugar for a vegetable", "Overconsumption can tint skin slightly orange"],
        image: "/images/vegetables/carrot.jpg",
    },
    {
        name: "Tomato",
        slug: "tomato",
        category: "vegetables",
        description: "A juicy, vibrant vegetable (botanically a fruit) that is the absolute best dietary source of lycopene.",
        nutrition: { calories: "18 kcal", vitaminC: "13.7 mg", lycopene: "2573 mcg", potassium: "237 mg" },
        pros: ["Extremely rich in lycopene", "Supports heart health", "Very low in calories"],
        cons: ["Highly acidic and can trigger reflux", "Nightshade family may cause inflammation in some"],
        image: "/images/vegetables/tomato.jpg",
    },
    {
        name: "Kale",
        slug: "kale",
        category: "vegetables",
        description: "One of the most nutrient-dense foods on earth, loaded with vitamins K, C, and calcium.",
        nutrition: { calories: "49 kcal", vitaminK: "389 mcg", vitaminC: "120 mg", calcium: "150 mg" },
        pros: ["Incredible nutrient density", "High calcium for bone health", "Great source of antioxidants"],
        cons: ["Tough texture when eaten raw", "Strong, earthy flavor isn't for everyone"],
        image: "/images/vegetables/kale.jpg",
    },
    {
        name: "Cauliflower",
        slug: "cauliflower",
        category: "vegetables",
        description: "A highly versatile cruciferous vegetable commonly used as a low-carb substitute for grains.",
        nutrition: { calories: "25 kcal", vitaminC: "48.2 mg", vitaminK: "15.5 mcg", fiber: "2 g" },
        pros: ["Excellent low-carb alternative", "High in vitamin C", "Contains antioxidants"],
        cons: ["Can cause digestive distress", "Bland flavor requires seasoning"],
        image: "/images/vegetables/cauliflower.jpg",
    },
    {
        name: "Bell Pepper",
        slug: "bell-pepper",
        category: "vegetables",
        description: "Crisp and refreshing peppers that offer an exceptionally high amount of immune-boosting vitamin C.",
        nutrition: { calories: "31 kcal", vitaminC: "127.7 mg", vitaminA: "157 mcg", antioxidants: "High" },
        pros: ["More vitamin C than an orange", "Rich in antioxidants", "Great crunch for salads"],
        cons: ["Nightshade vegetable", "Skin can be hard to digest for some"],
        image: "/images/vegetables/bell-pepper.jpg",
    },
    {
        name: "Cabbage",
        slug: "cabbage",
        category: "vegetables",
        description: "A hardy, affordable leafy vegetable that is a staple worldwide and great for gut health when fermented.",
        nutrition: { calories: "25 kcal", vitaminC: "36.6 mg", vitaminK: "76 mcg", fiber: "2.5 g" },
        pros: ["Excellent for gut health (especially fermented)", "Very shelf-stable", "Rich in vitamin K"],
        cons: ["Can cause bloating", "Strong smell when cooking"],
        image: "/images/vegetables/cabbage.jpg",
    },
    {
        name: "Sweet Potato",
        slug: "sweet-potato",
        category: "vegetables",
        description: "A starchy, naturally sweet root vegetable packed with beta-carotene and essential minerals.",
        nutrition: { calories: "86 kcal", betaCarotene: "8509 mcg", vitaminA: "709 mcg", potassium: "337 mg" },
        pros: ["Excellent complex carbohydrate", "Extremely high in vitamin A", "Supports gut health"],
        cons: ["Higher in calories and carbs", "High glycemic index if baked or mashed"],
        image: "/images/vegetables/sweet-potato.jpg",
    },
    {
        name: "Zucchini",
        slug: "zucchini",
        category: "vegetables",
        description: "A summer squash that is incredibly light, hydrating, and often used as a healthy pasta alternative.",
        nutrition: { calories: "17 kcal", vitaminC: "17.9 mg", potassium: "261 mg", fiber: "1 g" },
        pros: ["Very hydrating and low calorie", "Great low-carb pasta substitute", "Contains potassium"],
        cons: ["Can release too much water when cooking", "Relatively low in fiber"],
        image: "/images/vegetables/zucchini.jpg",
    },
    {
        name: "Asparagus",
        slug: "asparagus",
        category: "vegetables",
        description: "A premium spring vegetable rich in folate and vitamin K, known for its elegant flavor.",
        nutrition: { calories: "20 kcal", vitaminK: "41.6 mcg", folate: "52 mcg", fiber: "2.1 g" },
        pros: ["Excellent source of folate", "Acts as a natural diuretic", "High in vitamin K"],
        cons: ["Causes an odor in urine", "Expensive when out of season"],
        image: "/images/vegetables/asparagus.jpg",
    },
    {
        name: "Brussels Sprouts",
        slug: "brussels-sprouts",
        category: "vegetables",
        description: "Miniature cabbages that become nutty and delicious when roasted, offering a massive nutrient punch.",
        nutrition: { calories: "43 kcal", vitaminC: "85 mg", vitaminK: "177 mcg", fiber: "3.8 g" },
        pros: ["High fiber content", "Rich in vitamins C and K", "Great source of antioxidants"],
        cons: ["Strong bitter flavor if overcooked", "Can cause significant gas/bloating"],
        image: "/images/vegetables/brussels-sprouts.jpg",
    },
    {
        name: "Celery",
        slug: "celery",
        category: "vegetables",
        description: "A crunchy, hydrating stalk that provides a satisfying snap and valuable electrolytes with almost no calories.",
        nutrition: { calories: "16 kcal", vitaminK: "29.3 mcg", potassium: "260 mg", fiber: "1.6 g" },
        pros: ["Extremely low calorie", "Very hydrating", "Provides natural electrolytes"],
        cons: ["Stringy texture can be annoying", "Often heavily sprayed with pesticides"],
        image: "/images/vegetables/celery.jpg",
    },
    {
        name: "Beetroot",
        slug: "beetroot",
        category: "vegetables",
        description: "A vibrant earth-toned root famous for lowering blood pressure and enhancing athletic performance.",
        nutrition: { calories: "43 kcal", folate: "109 mcg", manganese: "0.3 mg", fiber: "2.8 g" },
        pros: ["Improves blood flow and stamina", "Rich in folate", "Contains potent betalain antioxidants"],
        cons: ["Can temporarily tint urine/stool red", "Earthy taste isn't for everyone", "High in sugar for a veggie"],
        image: "/images/vegetables/beetroot.jpg",
    },
    {
        name: "Onion",
        slug: "onion",
        category: "vegetables",
        description: "A foundational aromatic vegetable offering powerful antioxidants and immune-supportive compounds.",
        nutrition: { calories: "40 kcal", vitaminC: "7.4 mg", antioxidants: "High", fiber: "1.7 g" },
        pros: ["Rich in quercetin (antioxidant)", "Adds deep flavor to any dish", "Supports heart health"],
        cons: ["Causes bad breath", "Can irritate eyes when chopping", "May trigger acid reflux"],
        image: "/images/vegetables/onion.jpg",
    },
    {
        name: "Garlic",
        slug: "garlic",
        category: "vegetables",
        description: "A potent immune-boosting bulb relied upon worldwide for both its medicinal properties and incredible flavor.",
        nutrition: { calories: "149 kcal", manganese: "1.7 mg", vitaminB6: "1.2 mg", antioxidants: "High" },
        pros: ["Powerful immune booster", "Has antibacterial properties", "Enhances cardiovascular health"],
        cons: ["Causes lingering bad breath", "Can cause digestive upset in large amounts"],
        image: "/images/vegetables/garlic.jpg",
    },
    {
        name: "Radish",
        slug: "radish",
        category: "vegetables",
        description: "A peppery, crisp root vegetable that provides a refreshing bite and supports liver health.",
        nutrition: { calories: "16 kcal", vitaminC: "14.8 mg", potassium: "233 mg", fiber: "1.6 g" },
        pros: ["Very low in calories", "High in vitamin C", "Adds great crunch and spice"],
        cons: ["Pungent flavor can overpower dishes", "May cause digestive gas"],
        image: "/images/vegetables/radish.jpg",
    },
    {
        name: "Pumpkin",
        slug: "pumpkin",
        category: "vegetables",
        description: "A versatile autumn squash naturally sweet and loaded with beta-carotene for a healthy immune system.",
        nutrition: { calories: "26 kcal", betaCarotene: "3100 mcg", vitaminA: "426 mcg", fiber: "0.5 g" },
        pros: ["Rich in vitamin A for immunity", "Very low in calories", "Versatile for sweet/savory cooking"],
        cons: ["Low fiber compared to other squashes", "Difficult to cut and prep"],
        image: "/images/vegetables/pumpkin.jpg",
    },
    {
        name: "Turnip",
        slug: "turnip",
        category: "vegetables",
        description: "A mild, crisp root vegetable perfect for roasting or mashing as a lower-carb potato alternative.",
        nutrition: { calories: "28 kcal", vitaminC: "21 mg", calcium: "30 mg", fiber: "1.8 g" },
        pros: ["Good source of vitamin C", "Lower carb alternative to potatoes", "Edible greens and roots"],
        cons: ["Slightly bitter undertone", "Can be woody if grown too large"],
        image: "/images/vegetables/turnip.jpg",
    },
    {
        name: "Okra",
        slug: "okra",
        category: "vegetables",
        description: "A warm-climate pod vegetable rich in mucilage, which is excellent for digestive health and stabilizing blood sugar.",
        nutrition: { calories: "33 kcal", vitaminC: "23 mg", magnesium: "57 mg", fiber: "3.2 g" },
        pros: ["Great source of magnesium", "Promotes healthy gut flora", "Helps stabilize blood sugar"],
        cons: ["Slimy texture if not cooked properly", "Spoils quickly"],
        image: "/images/vegetables/okra.jpg",
    },
    {
        name: "Green Beans",
        slug: "green-beans",
        category: "vegetables",
        description: "Crisp and tender edible pods that deliver a balanced mix of fiber, vitamins, and minerals.",
        nutrition: { calories: "31 kcal", vitaminC: "12.2 mg", vitaminK: "14.4 mcg", fiber: "2.7 g" },
        pros: ["Great source of healthy fiber", "Contains silicon for bone health", "Low in calories"],
        cons: ["Contains lectins (reduced by cooking)", "Can be tough/stringy if overgrown"],
        image: "/images/vegetables/green-beans.jpg",
    },
    {
        name: "Peas",
        slug: "peas",
        category: "vegetables",
        description: "Sweet, starchy legumes that stand out from other vegetables due to their impressively high plant protein content.",
        nutrition: { calories: "81 kcal", vitaminC: "40 mg", vitaminK: "24.8 mcg", protein: "5.4 g" },
        pros: ["High plant-based protein", "Rich in fiber", "Sweet and kid-friendly"],
        cons: ["High in carbohydrates and calories", "Contains phytic acid"],
        image: "/images/vegetables/peas.jpg",
    },
    {
        name: "Eggplant",
        slug: "eggplant",
        category: "vegetables",
        description: "A meaty, sponge-like vegetable that perfectly absorbs flavors and boasts skin rich in nasunin antioxidants.",
        nutrition: { calories: "25 kcal", vitaminC: "2.2 mg", potassium: "229 mg", fiber: "3 g" },
        pros: ["Skin provides potent antioxidants", "Great meat substitute texture", "High in fiber"],
        cons: ["Sponge-like texture absorbs cooking oils heavily", "Nightshade family (can cause inflammation in some)"],
        image: "/images/vegetables/eggplant.jpg",
    },
    {
        name: "Leeks",
        slug: "leeks",
        category: "vegetables",
        description: "An elegant, milder relative of the onion, offering excellent prebiotics and sophisticated flavor.",
        nutrition: { calories: "61 kcal", vitaminK: "47 mcg", manganese: "0.5 mg", fiber: "1.8 g" },
        pros: ["Rich in prebiotic fiber for the gut", "Delicate, sweet onion flavor", "High in vitamin K"],
        cons: ["Notoriously difficult to clean off dirt", "Higher in calories than onions"],
        image: "/images/vegetables/leeks.jpg",
    },
    {
        name: "Artichoke",
        slug: "artichoke",
        category: "vegetables",
        description: "A unique thistle plant bursting with prebiotics and liver-supporting nutrients, though requiring careful prep.",
        nutrition: { calories: "47 kcal", vitaminC: "11.7 mg", magnesium: "60 mg", fiber: "5.4 g" },
        pros: ["Incredibly high in fiber", "Supports liver health", "Rich in prebiotics"],
        cons: ["Time consuming and difficult to prepare", "Low yield for the amount of work required"],
        image: "/images/vegetables/artichoke.jpg",
    },
    {
        name: "Mustard Greens",
        slug: "mustard-greens",
        category: "vegetables",
        description: "Peppery, pungent leafy greens loaded with vitamin K and deeply beneficial plant compounds.",
        nutrition: { calories: "27 kcal", vitaminK: "256 mcg", vitaminA: "105 mcg", fiber: "3.2 g" },
        pros: ["Very high in vitamin K", "Strong detoxifying properties", "High fiber"],
        cons: ["Bitter and spicy taste", "Often requires cooking to mellow flavor"],
        image: "/images/vegetables/mustard-greens.jpg",
    },
    {
        name: "Collard Greens",
        slug: "collard-greens",
        category: "vegetables",
        description: "Sturdy, robust greens that serve as a southern staple and an exceptional source of dietary calcium.",
        nutrition: { calories: "32 kcal", vitaminK: "500 mcg", calcium: "232 mg", fiber: "4 g" },
        pros: ["Excellent plant source of calcium", "Binds bile acids to lower cholesterol", "Extremely high in vitamin K"],
        cons: ["Requires long cooking times to become tender", "High vitamin K can interact with blood thinners"],
        image: "/images/vegetables/collard-greens.jpg",
    },
    {
        name: "Swiss Chard",
        slug: "swiss-chard",
        category: "vegetables",
        description: "A beautiful, colorful leafy green related to beets, boasting massive amounts of magnesium and vitamin K.",
        nutrition: { calories: "19 kcal", vitaminK: "830 mcg", magnesium: "81 mg", fiber: "1.6 g" },
        pros: ["Phenomenal source of vitamin K", "Rich in blood-pressure easing magnesium", "Colorful antioxidant stems"],
        cons: ["High in oxalates (can form kidney stones)", "Earthy taste akin to beets"],
        image: "/images/vegetables/swiss-chard.jpg",
    },
    {
        name: "Bok Choy",
        slug: "bok-choy",
        category: "vegetables",
        description: "A crisp, delicate Chinese cabbage that cooks quickly and delivers gentle flavor with high nutrients.",
        nutrition: { calories: "13 kcal", vitaminC: "45 mg", vitaminK: "46 mcg", fiber: "1 g" },
        pros: ["Very fast to cook", "Great source of vitamin C", "Lower in oxalates than spinach"],
        cons: ["Wilts and goes bad quickly", "Holds a lot of water weight"],
        image: "/images/vegetables/bok-choy.jpg",
    },
    {
        name: "Arugula",
        slug: "arugula",
        category: "vegetables",
        description: "A sharp, peppery salad green naturally high in nitrates that boost athletic performance and cardiovascular health.",
        nutrition: { calories: "25 kcal", vitaminK: "109 mcg", vitaminA: "119 mcg", fiber: "1.6 g" },
        pros: ["High dietary nitrates for blood flow", "Adds great peppery flavor", "Contains cancer-fighting glucosinolates"],
        cons: ["Flavor can be too bitter/spicy for some", "Wilts very quickly"],
        image: "/images/vegetables/arugula.jpg",
    },
    {
        name: "Dandelion Greens",
        slug: "dandelion-greens",
        category: "vegetables",
        description: "A potent, deeply bitter green often used in herbal medicine to stimulate the liver and digestion.",
        nutrition: { calories: "45 kcal", vitaminK: "778 mcg", vitaminA: "508 mcg", calcium: "187 mg" },
        pros: ["Excellent liver support", "Extremely high in vitamins A and K", "Rich in calcium"],
        cons: ["Intensely bitter", "Foraged greens may carry pesticides if not careful"],
        image: "/images/vegetables/dandelion-greens.jpg",
    },
    {
        name: "Watercress",
        slug: "watercress",
        category: "vegetables",
        description: "An aquatic leafy green repeatedly ranked as one of the most nutrient-dense foods in existence per calorie.",
        nutrition: { calories: "11 kcal", vitaminK: "250 mcg", vitaminC: "43 mg", calcium: "120 mg" },
        pros: ["Off-the-charts nutrient density score", "Contains specialized anti-cancer compounds", "Very low calories"],
        cons: ["Highly perishable", "Can harbor aquatic parasites if harvested from wild water"],
        image: "/images/vegetables/watercress.jpg",
    },
    {
        name: "Chili Pepper",
        slug: "chili-pepper",
        category: "vegetables",
        description: "Fiery peppers loaded with capsaicin, which boosts metabolism and provides immense vitamin C.",
        nutrition: { calories: "40 kcal", vitaminC: "143.7 mg", capsaicin: "High", fiber: "1.5 g" },
        pros: ["Capsaicin boosts metabolism and pain relief", "Massive vitamin C content", "Adds incredible flavor without calories"],
        cons: ["Can cause severe heartburn/indigestion", "Oils can painfully burn eyes and skin"],
        image: "/images/vegetables/chili-pepper.jpg",
    },
    {
        name: "Scallions",
        slug: "scallions",
        category: "vegetables",
        description: "Also known as green onions, offering a milder onion flavor alongside ample vitamin K.",
        nutrition: { calories: "32 kcal", vitaminK: "207 mcg", vitaminC: "18.8 mg", fiber: "2.6 g" },
        pros: ["Excellent source of vitamin K", "Versatile delicate garnish", "Digestively gentler than mature onions"],
        cons: ["Go slimy very quickly in the fridge", "Mild flavor fades quickly when cooked"],
        image: "/images/vegetables/scallions.jpg",
    },
    {
        name: "Fennel",
        slug: "fennel",
        category: "vegetables",
        description: "A crisp, aromatic bulb with an anise-like flavor, historically used to aid digestion.",
        nutrition: { calories: "31 kcal", vitaminC: "12 mg", potassium: "414 mg", fiber: "3.1 g" },
        pros: ["Natural digestive aid", "High in potassium", "Crunchy and refreshing"],
        cons: ["Anise/licorice flavor is polarizing", "Can be woody if older"],
        image: "/images/vegetables/fennel.jpg",
    },
    {
        name: "Parsnip",
        slug: "parsnip",
        category: "vegetables",
        description: "A pale root mimicking a carrot in shape but offering a sweet, earthy, nut-like profile rich in fiber.",
        nutrition: { calories: "75 kcal", vitaminC: "17 mg", potassium: "375 mg", fiber: "4.9 g" },
        pros: ["Excellent source of dietary fiber", "Rich in potassium", "Deep, satisfying flavor"],
        cons: ["Higher in sugar and calories than carrots", "Starchy texture requires cooking"],
        image: "/images/vegetables/parsnip.jpg",
    },
    {
        name: "Yam",
        slug: "yam",
        category: "vegetables",
        description: "A starchy, energy-dense tuber providing sustained complex carbs and plenty of potassium.",
        nutrition: { calories: "118 kcal", vitaminC: "17.1 mg", potassium: "816 mg", fiber: "4.1 g" },
        pros: ["Massive potassium content", "Great sustained energy source", "High in fiber"],
        cons: ["Calorie and carb dense", "Must be cooked to neutralize toxins"],
        image: "/images/vegetables/yam.jpg",
    },
    {
        name: "Butternut Squash",
        slug: "butternut-squash",
        category: "vegetables",
        description: "A sweet, nutty winter squash boasting massive reserves of vitamin A and a silky cooked texture.",
        nutrition: { calories: "45 kcal", vitaminA: "532 mcg", vitaminC: "21 mg", fiber: "2 g" },
        pros: ["Incredible source of vitamin A", "Supports eye and skin health", "Sweet comfort food alternative"],
        cons: ["Painful and difficult to peel/cut raw", "Skin can cause temporary contact dermatitis"],
        image: "/images/vegetables/butternut-squash.jpg",
    },
    {
        name: "Chayote",
        slug: "chayote",
        category: "vegetables",
        description: "A mild, crisp gourd popular in Latin American cuisine, excellent for absorbing surrounding flavors.",
        nutrition: { calories: "19 kcal", vitaminC: "7.7 mg", folate: "93 mcg", fiber: "1.7 g" },
        pros: ["Very low in calories", "Good source of folate", "Refreshing crunch similar to water chestnuts"],
        cons: ["Requires peeling due to tough skin", "Raw skin sap can numb hands"],
        image: "/images/vegetables/chayote.jpg",
    },
    {
        name: "Kohlrabi",
        slug: "kohlrabi",
        category: "vegetables",
        description: "An odd-looking but delicious brassica with a taste matching the stem of broccoli, delivering intense vitamin C.",
        nutrition: { calories: "27 kcal", vitaminC: "62 mg", potassium: "350 mg", fiber: "3.6 g" },
        pros: ["Very high in vitamin C", "Excellent crunch and fiber", "Long shelf life"],
        cons: ["Thick fibrous peel requires heavy trimming", "Often difficult to find in standard markets"],
        image: "/images/vegetables/kohlrabi.jpg",
    },
    {
        name: "Seaweed",
        slug: "seaweed",
        category: "vegetables",
        description: "A marine vegetable providing a unique baseline of trace minerals, most notably an abundance of iodine.",
        nutrition: { calories: "45 kcal", iodine: "High", vitaminK: "66 mcg", fiber: "5 g" },
        pros: ["Essential iodine for thyroid function", "High in rare trace minerals", "Rich umami flavor"],
        cons: ["Can easily exceed safe iodine limits", "May contain heavy metals from ocean waters"],
        image: "/images/vegetables/seaweed.jpg",
    },
    {
        name: "Mushrooms",
        slug: "mushrooms",
        category: "vegetables",
        description: "While technically fungi, these are beloved savory veggies providing rare dietary vitamin D and selenium.",
        nutrition: { calories: "22 kcal", vitaminD: "Exposure dependent", selenium: "9.3 mcg", fiber: "1 g" },
        pros: ["One of the only natural food sources of Vitamin D", "Contains selenium (antioxidant) ", "Flavorful meat substitute"],
        cons: ["Can absorb heavy metals from soil", "Texture issues for some people"],
        image: "/images/vegetables/mushrooms.jpg",
    },
    {
        name: "Cucumber",
        slug: "cucumber",
        category: "vegetables",
        description: "A supremely crisp and hydrating vegetable composed of 95% water, perfect for glowing skin and cooling hydration.",
        nutrition: { calories: "16 kcal", vitaminK: "16.4 mcg", potassium: "147 mg", fiber: "0.5 g" },
        pros: ["Extremely hydrating", "Flushes toxins from the body", "Very low in calories"],
        cons: ["Low nutrient density compared to dark greens", "Often waxed thickly (requires peeling or organic)"],
        image: "/images/vegetables/cucumber.jpg",
    },
    {
        name: "Lotus Root",
        slug: "lotus-root",
        category: "vegetables",
        description: "A stunning, hole-filled aquatic stalk offering a satisfying crunch, plenty of vitamin C, and robust dietary fiber.",
        nutrition: { calories: "74 kcal", vitaminC: "44 mg", potassium: "556 mg", fiber: "4.9 g" },
        pros: ["Distinctive, beautiful shape for cooking", "Very high in potassium", "Rich in vitamin C"],
        cons: ["Must be peeled and cooked thoroughly", "Not available in all regions"],
        image: "/images/vegetables/lotus-root.jpg",
    }
];

export function getFoodsByCategory(categorySlug: string): FoodItem[] {
    return foods.filter((food) => food.category === categorySlug);
}

export function getFoodBySlug(slug: string): FoodItem | undefined {
    return foods.find((food) => food.slug === slug);
}

export function getFeaturedFoods(count: number = 4): FoodItem[] {
    return foods.slice(0, count);
}

